services:
  dns:
    build: .
    container_name: bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./logs:/var/log          # 필요하면 미리 mkdir logs
    restart: unless-stopped
